#                     _|            _|
# _|  _|_|    _|_|_|      _|_|_|    _|_|_|      _|_|    _|      _|      _|    _|_|_|
# _|_|      _|    _|  _|  _|    _|  _|    _|  _|    _|  _|      _|      _|  _|    _|
# _|        _|    _|  _|  _|    _|  _|    _|  _|    _|    _|  _|  _|  _|    _|    _|
# _|          _|_|_|  _|  _|    _|  _|_|_|      _|_|        _|      _|        _|_|_|
#                                                                                 _|
#                                                                                 _|

# Meta
[meta.last]
dt = 2023-08-31T00:08:56Z
editor = 'maroda@rainbowq.io'

[org.aws]
account = '696025759092'

# Infrastructure
[infra.sme]
chaos = 'maroda@rainbowq.io'
kafka = 'maroda@rainbowq.io'
sumologic = 'maroda@rainbowq.io'
terraform = 'maroda@rainbowq.io'

# Production Engineering Group
[peg.bastion]
os = 'centos-7-v20210217'
image = 'beki'

[peg.techscope]
radar = 'techscope.aws.io:8000/radar/'

# Salt Masterless Minion tools
[peg.salt]
states = 's3://salt-tree-prod.aws.io'
pillar = 's3://salt-pillar-prod.aws.io'
apply = 'salt-minion --local state.apply'
sync = 'aws s3 sync --delete s3://salt-tree-prod.aws.io /srv/salt && aws s3 sync --delete s3://salt-pillar-prod.aws.io /srv/pillar'
