#                     _|            _|
# _|  _|_|    _|_|_|      _|_|_|    _|_|_|      _|_|    _|      _|      _|    _|_|_|
# _|_|      _|    _|  _|  _|    _|  _|    _|  _|    _|  _|      _|      _|  _|    _|
# _|        _|    _|  _|  _|    _|  _|    _|  _|    _|    _|  _|  _|  _|    _|    _|
# _|          _|_|_|  _|  _|    _|  _|_|_|      _|_|        _|      _|        _|_|_|
#                                                                                 _|
#                                                                                 _|

# Meta
[meta.last]
dt = 2021-03-30T22:00:00Z
editor = 'maroda@rainbowq.io'

# Blameless GCP
[blameless.gcp]
project = 'blameless-185322'
editor = 'matt@blameless.com'

[blameless.aws]
account = '696025759092'

# Infrastructure
[infra.sme]
chaos = 'matt@blameless.com'
kafka = 'matt@blameless.com'
kubernetes = 'darrell@blameless.com'
slo = 'afif@blameless.com'
snyk = 'geoffw@blameless.com'
sre = 'darrell@blameless.com'
sumologic = 'matt@blameless.com'
terraform = 'matt@blameless.com'

# Production Engineering Group
[peg.bastion]
os = 'centos-7-v20210217'
image = 'beki'

[peg.techscope]
radar = 'techscope.blamelessaws.io:8000/radar/'

# Salt Masterless Minion tools
[peg.salt]
states = 's3://salt-tree-prod.blamelessaws.io'
pillar = 's3://salt-pillar-prod.blamelessaws.io'
apply = 'salt-minion --local state.apply'
sync = 'aws s3 sync --delete s3://salt-tree-prod.blamelessaws.io /srv/salt && aws s3 sync --delete s3://salt-pillar-prod.blamelessaws.io /srv/pillar'

# Blameless Deployed Instances (see ./bag/README.md)
[blameless.deploy.instance]
test_helm_versions = true
blamelesstrial = true
blamelessdev = true
testautomation = true
hold = true
hold-ha = true
hold-cre = true
hold-blameless = true
blameless = true
blamelesscre = true
blamelessdemo = true
checkr = true
iterable = true
masterclass = true
packet = true
platform9 = true
procore = true
tenable = true
homedepot = true
flywire = true
underarmour = true
datarobot = true
mambu = true
addepar = true
earnin = true
postmates = true
acs = true
labelbox = true
missionlane = true
vital = true
citrix = true
mercari-sandbox = true
mercari = true
gojek = true
allegro = true
greenlight = true
gremlin = true
zapier = true
inloco = true
cruise = true
mux = true
flatiron = true
hashicorp = true
revops = true
zoopla = true
fast = true
hitachisolutions = true
ticketmaster = true
fox = true
eventbrite = true
demo = true
crowdstrike = true
markley = true
paymentsense = true
cultureamp = true
marqeta = true
twitch = true
lntinfotech = true
petalcard = true
paloaltonetworks = true
appsflyer = true
bandwidth = true
stubhub = true
stitchfix = true
intercom = true
afterpay = true
dremio = true
caffeine = true
alpha-sense = true
ytel = true
aiven = true
jupiterone = true
sadapay = true
glovoapp = true
qonto = true
color = true
adarga = true
smartthings = true
load-test = true
belcorp = true
myfitnesspal = true
benevity = true
agero = true
newrelic = true
sezzle = true
zeotap = true
flymachine = true
coxautoinc = true
nvidia = true
europe-test = true
asia-test = true
