#                     _|            _|
# _|  _|_|    _|_|_|      _|_|_|    _|_|_|      _|_|    _|      _|      _|    _|_|_|
# _|_|      _|    _|  _|  _|    _|  _|    _|  _|    _|  _|      _|      _|  _|    _|
# _|        _|    _|  _|  _|    _|  _|    _|  _|    _|    _|  _|  _|  _|    _|    _|
# _|          _|_|_|  _|  _|    _|  _|_|_|      _|_|        _|      _|        _|_|_|
#                                                                                 _|
#                                                                                 _|

# Meta
[meta.last]
dt = 2021-03-30T22:00:00Z
editor = 'maroda@rainbowq.io'

# Org GCP
[org.gcp]
project = 'org-185322'
editor = 'maroda@rainbowq.io'

[org.aws]
account = '696025759092'

# Infrastructure
[infra.sme]
chaos = 'maroda@rainbowq.io'
kafka = 'maroda@rainbowq.io'
sumologic = 'maroda@rainbowq.io'
terraform = 'maroda@rainbowq.io'

# Production Engineering Group
[peg.bastion]
os = 'centos-7-v20210217'
image = 'beki'

[peg.techscope]
radar = 'techscope.aws.io:8000/radar/'

# Salt Masterless Minion tools
[peg.salt]
states = 's3://salt-tree-prod.aws.io'
pillar = 's3://salt-pillar-prod.aws.io'
apply = 'salt-minion --local state.apply'
sync = 'aws s3 sync --delete s3://salt-tree-prod.aws.io /srv/salt && aws s3 sync --delete s3://salt-pillar-prod.aws.io /srv/pillar'

# Deployed Instances
[org.prod.instance]
addepar = "gke_prod-us-central1-private-c"
earnin = "gke_prod-us-central1-private-c"
flywire = "gke_prod-europe-west4-private-a"
demo = "gke_prod-us-central1-private-c"
mercari = "eks_prod-ap-northeast-1-private-mt"
gojek = "eks_prod-ap-northeast-1-private-mt"
ticketmaster = "gke_prod-us-central1-private-a"
